[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "RawNetPrintPlugin"
version = "0.0.3"
authors = [
    { name = "Jake Armstrong", email="jakea@kalogon.com" },
]
